server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/sale-db?useSSL=true&requireSSL=false&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update